import { useEffect, useState } from 'react'
import { ArrowLeft, Check, Download, FileUp, MessageSquare, Paperclip, Plus, Trash2 } from 'lucide-react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { PageHeader } from '@/components/layout/PageHeader'
import { LoadingState } from '@/components/ui/LoadingState'
import { getTaskById, listTaskHistory, updateTask, createTask } from '@/features/tasks/services/tasks.service'
import { createChecklistItem, deleteChecklistItem, listChecklist, setChecklistItemCompleted } from '@/features/checklists/services/checklists.service'
import { createComment, listComments, resolveQuestion } from '@/features/comments/services/comments.service'
import { createSignedEvidenceUrl, listAttachments, removeAttachment, uploadAttachment } from '@/features/attachments/services/attachments.service'
import { useProjectData } from '@/hooks/useProjectData'
import { useProject } from '@/features/projects/ProjectProvider'
import { useAuth } from '@/features/auth/AuthProvider'
import { listMembers } from '@/features/core/core.service'
import type { TaskPriority, TaskStatus } from '@/types/database'
import { useOperationalRelations } from '@/features/operations/hooks/useOperationalRelations'
import { Flag, ShieldAlert } from 'lucide-react'

export function TaskDetailPage() {
  const { taskId } = useParams(); const isNew = taskId === 'nova'; const { project } = useProject(); const { user } = useAuth(); const navigate = useNavigate(); const client = useQueryClient(); const projectData = useProjectData()
  const task = useQuery({ queryKey: ['task', taskId], enabled: !isNew, queryFn: () => getTaskById(taskId!) })
  const relations = useOperationalRelations()
  const members = useQuery({ queryKey: ['members', project?.id], enabled: Boolean(project), queryFn: () => listMembers(project!.id) })
  const checklist = useQuery({ queryKey: ['checklist', taskId], enabled: !isNew, queryFn: () => listChecklist(taskId!) })
  const comments = useQuery({ queryKey: ['comments', taskId], enabled: !isNew, queryFn: () => listComments(taskId!) })
  const history = useQuery({ queryKey: ['history', taskId], enabled: !isNew, queryFn: () => listTaskHistory(taskId!) })
  const attachments = useQuery({ queryKey: ['attachments', taskId], enabled: !isNew, queryFn: () => listAttachments(taskId!) })
  const [form, setForm] = useState({ title: '', description: '', status: 'not_started' as TaskStatus, priority: 'medium' as TaskPriority, start_date: '', due_date: '', area_id: '', stage_id: '', primary_responsible_user_id: '', approver_user_id: '', blocked_reason: '', evidence_required: false, approval_required: false })
  const [newItem, setNewItem] = useState(''); const [comment, setComment] = useState(''); const [message, setMessage] = useState('')
  useEffect(() => { if (task.data) setForm({ title: task.data.title, description: task.data.description ?? '', status: task.data.status, priority: task.data.priority, start_date: task.data.start_date ?? '', due_date: task.data.due_date ?? '', area_id: task.data.area_id ?? '', stage_id: task.data.stage_id ?? '', primary_responsible_user_id: task.data.primary_responsible_user_id ?? '', approver_user_id: task.data.approver_user_id ?? '', blocked_reason: task.data.blocked_reason ?? '', evidence_required: task.data.evidence_required, approval_required: task.data.approval_required }) }, [task.data])
  const save = useMutation({ mutationFn: async () => isNew ? createTask({ project_id: project!.id, title: form.title, description: form.description || null, status: form.status, priority: form.priority, start_date: form.start_date || null, due_date: form.due_date || null, area_id: form.area_id || null, stage_id: form.stage_id || null, primary_responsible_user_id: form.primary_responsible_user_id || null, approver_user_id: form.approver_user_id || null, blocked_reason: form.status === 'blocked' ? form.blocked_reason : null, evidence_required: form.evidence_required, approval_required: form.approval_required }) : updateTask(taskId!, { ...form, description: form.description || null, start_date: form.start_date || null, due_date: form.due_date || null, area_id: form.area_id || null, stage_id: form.stage_id || null, primary_responsible_user_id: form.primary_responsible_user_id || null, approver_user_id: form.approver_user_id || null, blocked_reason: form.status === 'blocked' ? form.blocked_reason : null }), onSuccess: (saved) => { client.invalidateQueries({ queryKey: ['project-data'] }); if (isNew) navigate(`/app/tarefas/${saved.id}`, { replace: true }); else { client.invalidateQueries({ queryKey: ['task', taskId] }); setMessage('Alterações salvas.') } }, onError: (error) => setMessage(error instanceof Error ? error.message : 'Não foi possível salvar.') })
  if (!isNew && task.isLoading) return <LoadingState />
  return <><PageHeader eyebrow={isNew ? 'Nova tarefa' : 'Detalhes da tarefa'} title={form.title || 'Tarefa sem título'} description={isNew ? 'Crie uma entrega no projeto.' : `Progresso automático: ${task.data?.completion_percentage ?? 0}%`} actions={<><Link className="secondary-button" to="/app/tarefas"><ArrowLeft size={16}/> Voltar</Link><button className="primary-button" onClick={() => save.mutate()} disabled={!form.title || save.isPending}>{save.isPending ? 'Salvando…' : 'Salvar'}</button></>} />
    {!isNew && <nav className="task-context-links" aria-label="Contexto operacional da tarefa">
      {task.data?.area_id ? <Link to={`/app/areas/${task.data.area_id}`}>Área: {projectData.data?.areas.find((area) => area.id === task.data?.area_id)?.name ?? 'Abrir área'}</Link> : <span>Sem área definida</span>}
      {task.data?.stage_id ? <Link to={`/app/tarefas?stage=${task.data.stage_id}`}>Etapa: {projectData.data?.stages.find((stage) => stage.id === task.data?.stage_id)?.name ?? 'Abrir etapa'}</Link> : <span>Sem etapa definida</span>}
    </nav>}
    {message && <div className="inline-notice">{message}</div>}
    <div className="task-detail-grid"><main className="task-main"><section className="panel form-grid">
      <label className="field field-wide"><span>Título</span><input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })}/></label>
      <label className="field field-wide"><span>Descrição</span><textarea rows={5} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })}/></label>
      <Select label="Status" value={form.status} onChange={(v) => setForm({ ...form, status: v as TaskStatus })} options={['not_started','in_progress','waiting_external','blocked','under_review','completed','cancelled']}/>
      <Select label="Prioridade" value={form.priority} onChange={(v) => setForm({ ...form, priority: v as TaskPriority })} options={['critical','high','medium','low']}/>
      <label className="field"><span>Início</span><input type="date" value={form.start_date} onChange={(e) => setForm({ ...form, start_date: e.target.value })}/></label><label className="field"><span>Vencimento</span><input type="date" value={form.due_date} onChange={(e) => setForm({ ...form, due_date: e.target.value })}/></label>
      <Select label="Área" value={form.area_id} onChange={(v) => setForm({ ...form, area_id: v })} options={projectData.data?.areas.map((a) => ({ value: a.id, label: a.name })) ?? []}/>
      <Select label="Etapa" value={form.stage_id} onChange={(v) => setForm({ ...form, stage_id: v })} options={projectData.data?.stages.map((s) => ({ value: s.id, label: s.name })) ?? []}/>
      <Select label="Responsável" value={form.primary_responsible_user_id} onChange={(v) => setForm({ ...form, primary_responsible_user_id: v })} options={members.data?.map((m) => ({ value: m.user_id, label: m.profile.full_name })) ?? []}/>
      <Select label="Aprovador" value={form.approver_user_id} onChange={(v) => setForm({ ...form, approver_user_id: v })} options={members.data?.map((m) => ({ value: m.user_id, label: m.profile.full_name })) ?? []}/>
      {form.status === 'blocked' && <label className="field field-wide"><span>Motivo do bloqueio</span><textarea value={form.blocked_reason} onChange={(e) => setForm({ ...form, blocked_reason: e.target.value })}/></label>}
    </section>
    {!isNew && <><Section title="Checklist" icon={<Check size={18}/>}><div className="progress-track"><i style={{ width: `${task.data?.completion_percentage ?? 0}%` }}/></div><form className="inline-form" onSubmit={async (e) => { e.preventDefault(); if (!newItem) return; await createChecklistItem(taskId!, newItem, checklist.data?.length ?? 0); setNewItem(''); client.invalidateQueries({ queryKey: ['checklist', taskId] }); client.invalidateQueries({ queryKey: ['task', taskId] }) }}><input value={newItem} onChange={(e) => setNewItem(e.target.value)} placeholder="Novo item"/><button><Plus size={16}/></button></form>{checklist.data?.map((item) => <div className="check-item" key={item.id}><input type="checkbox" checked={item.completed} onChange={async (e) => { await setChecklistItemCompleted(item.id, e.target.checked); client.invalidateQueries({ queryKey: ['checklist', taskId] }); client.invalidateQueries({ queryKey: ['task', taskId] }) }}/><span>{item.title}</span><button onClick={async () => { await deleteChecklistItem(item.id); client.invalidateQueries({ queryKey: ['checklist', taskId] }) }}><Trash2 size={15}/></button></div>)}</Section>
    <Section title="Comentários e perguntas" icon={<MessageSquare size={18}/>}><form className="inline-form" onSubmit={async (e) => { e.preventDefault(); if (!comment || !user) return; await createComment({ taskId: taskId!, userId: user.id, content: comment }); setComment(''); client.invalidateQueries({ queryKey: ['comments', taskId] }) }}><input value={comment} onChange={(e) => setComment(e.target.value)} placeholder="Escreva um comentário…"/><button>Enviar</button></form>{comments.data?.map((item) => <article className="comment" key={item.id}><strong>{members.data?.find((m) => m.user_id === item.user_id)?.profile.full_name ?? 'Integrante'}</strong><p>{item.content}</p><small>{new Date(item.created_at).toLocaleString('pt-BR')} · {item.comment_type}</small>{item.comment_type === 'question' && !item.resolved && <button onClick={async () => { await resolveQuestion(item.id, user!.id); client.invalidateQueries({ queryKey: ['comments', taskId] }) }}>Marcar resolvida</button>}</article>)}</Section>
    <Section title="Anexos" icon={<Paperclip size={18}/>}><label className="upload-button"><FileUp size={17}/> Enviar arquivo<input type="file" hidden onChange={async (e) => { const file = e.target.files?.[0]; if (file && project && user) { await uploadAttachment(project.id, taskId!, user.id, file); client.invalidateQueries({ queryKey: ['attachments', taskId] }) } }}/></label>{attachments.data?.length ? attachments.data.map((file) => <div className="file-row" key={file.id}><span>{file.file_name}<small>{file.file_size ? `${Math.round(file.file_size / 1024)} KB` : ''}</small></span><button aria-label={`Baixar ${file.file_name}`} onClick={async () => window.open(await createSignedEvidenceUrl(file.storage_path), '_blank')}><Download size={16}/></button><button aria-label={`Remover ${file.file_name}`} onClick={async () => { await removeAttachment(file.id, file.storage_path); client.invalidateQueries({ queryKey: ['attachments', taskId] }) }}><Trash2 size={16}/></button></div>) : <p className="empty-inline">Nenhum anexo nesta tarefa.</p>}</Section>
    <Section title="Evidências relacionadas" icon={<Paperclip size={18}/>}>{relations.data?.evidence.filter((item) => item.task_id === taskId).length ? relations.data.evidence.filter((item) => item.task_id === taskId).map((item) => <div className="relation-row" key={item.id}><span>{item.title}<small>{relations.data?.categories.find((category) => category.id === item.category_id)?.name ?? 'Sem categoria'} · {item.due_date ?? 'Sem prazo'}</small></span><small>{item.completed_at || item.storage_path || item.external_url ? 'Disponível' : 'Pendente'}</small></div>) : <p className="empty-inline">{task.data?.evidence_required ? 'Evidência obrigatória ainda não registrada.' : 'Nenhuma evidência relacionada a esta tarefa.'}</p>}</Section>
    <Section title="Marcos relacionados" icon={<Flag size={18}/>}>{relations.data?.milestoneLinks.filter((link) => link.task_id === taskId).length ? relations.data.milestoneLinks.filter((link) => link.task_id === taskId).map((link) => { const milestone = projectData.data?.milestones.find((item) => item.id === link.milestone_id); return milestone ? <Link className="relation-row" to={`/app/marcos/${milestone.id}`} key={link.id}>{milestone.title}<span>{milestone.milestone_date ?? 'Sem data'}</span></Link> : null }) : <p className="empty-inline">Não existem marcos vinculados diretamente a esta tarefa.</p>}</Section>
    <Section title="Riscos relacionados" icon={<ShieldAlert size={18}/>}><p className="empty-inline">O schema não possui relação explícita entre riscos e tarefas.</p></Section>
    <Section title="Histórico" icon={<MessageSquare size={18}/>}><div className="history-line">{history.data?.length ? history.data.map((entry) => <div key={entry.id}><i/><span><strong>{entry.action}</strong> {entry.field_name && `em ${entry.field_name}`}<small>{entry.old_value !== null ? `De ${JSON.stringify(entry.old_value)} ` : ''}{entry.new_value !== null ? `para ${JSON.stringify(entry.new_value)} · ` : ''}{relations.data?.profiles.find((profile) => profile.id === entry.user_id)?.full_name ?? 'Sistema'} · {new Date(entry.created_at).toLocaleString('pt-BR')}</small></span></div>) : <p className="empty-inline">Nenhuma alteração registrada.</p>}</div></Section></>}
    </main><aside className="task-side panel"><h3>Requisitos</h3><label><input type="checkbox" checked={form.evidence_required} onChange={(e) => setForm({ ...form, evidence_required: e.target.checked })}/> Evidência obrigatória</label><label><input type="checkbox" checked={form.approval_required} onChange={(e) => setForm({ ...form, approval_required: e.target.checked })}/> Aprovação obrigatória</label></aside></div>
  </>
}

function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: (string | { value: string; label: string })[] }) { return <label className="field"><span>{label}</span><select value={value} onChange={(e) => onChange(e.target.value)}><option value="">Não definido</option>{options.map((option) => { const item = typeof option === 'string' ? { value: option, label: option.replaceAll('_', ' ') } : option; return <option key={item.value} value={item.value}>{item.label}</option> })}</select></label> }
function Section({ title, icon, children }: { title: string; icon: React.ReactNode; children: React.ReactNode }) { return <section className="panel detail-section"><header>{icon}<h2>{title}</h2></header>{children}</section> }
